name: Node

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm install -g @vscode/vsce
        vsce package
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: vsix
        path: ROCgdb-extension/rocgdb-extension-0.1.0.vsix
